DEVICE          : cuda                        # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'exp/MDDG-B2'          # output folder name used for saving the model, logs and inference results
GPUs            : 4
GPU_IDs         : [0, 1, 2, 4]
USE_WANDB       : False
WANDB_NAME      : 'MMSF-FMB3-MF'             # name for the run

MODEL:
  NAME          : MDDG                                         # name of the model you are using
  BACKBONE      : MDDG-B2                                      # model variant
  PRETRAINED    : 'checkpoints/pretrained/segformer/mit_b2.pth'     # backbone model's weight
  RESUME        :  ""                                                 # path to the model you want to resume training

DATASET:
  NAME          : MF                                               # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/data/tangchen/MFNet/'                           # dataset root path
  IGNORE_LABEL  : 255
  # MODALS        : ['img']
  MODALS        : ['img', 'thermal'] 

TRAIN:
  IMAGE_SIZE    : [480, 640]       # training image size in (h, w) === Fixed in dataloader, following MCubeSNet
  BATCH_SIZE    : 3               # batch size used to train
  EPOCHS        : 500             # number of epochs to train
  EVAL_START    : 200             # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : False           # use AMP in training 启用后容易发生溢出
  DDP           : true            # use DDP training
  
LOSS:
  NAME          : OhemCrossEntropy # loss function name
  CLS_WEIGHTS   :                  # use class weights in loss calculation
  AUX_LOSS      : true
  BATCHFORMER   : 

OPTIMIZER:
  NAME          : adamw           # optimizer name 可以尝试使用sgd adamw虽然收敛快但是效果可能不好
  LR            : 0.0001         # initial learning rate used in optimizer     0.00006 
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  
EVAL:
  MODEL_PATH    : "/data/tangchen/MDDG/exp/MDDG-B2/MMSF-FMB3-MF/2025_01_06_13:11:31/MDDG_MDDG-B2_MF_epoch398_62.4.pth"               # Path to your saved model
  IMAGE_SIZE    : [480, 640]                            # evaluation image size in (h, w)
  BATCH_SIZE    : 8                                    # batch size
  VIS_SAVE_DIR  : '/data/tangchen/MDDG/Vis'              # Where to save visualization
  MSF:
    ENABLE      : False                                   # multi-scale and flip evaluation
    FLIP        : true                                    # use flip in evaluation
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation